%s=61;
%e=68;
s=60;
e=68;
load('q2.mat');
x=poisson_insulate(128,4,8);
part=x(s:e,:);
heatmap(part.','Colormap',copper);
% xlabel('$\frac{x}{\Delta x}$','Interpreter','latex');
% ylabel('$\frac{y}{\Delta y}$','Interpreter','latex');
